[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
first = "z2pvAcWzBL3KgptqswvywX2mi7FR3eQwoECGrfTJiDB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
